cls
call KENSSharp.exe -r n "8x8 - GHZ1.nem"
call KENSSharp.exe -r n "8x8 - GHZ2.nem"
call KENSSharp.exe -r n "8x8 - LZ.nem"
call KENSSharp.exe -r n "8x8 - MZ.nem"
call KENSSharp.exe -r n "8x8 - SBZ.nem"
call KENSSharp.exe -r n "8x8 - SLZ.nem"
call KENSSharp.exe -r n "8x8 - SYZ.nem"
call KENSSharp.exe -r n "Animal Chicken.nem"
call KENSSharp.exe -r n "Animal Flicky.nem"
call KENSSharp.exe -r n "Animal Penguin.nem"
call KENSSharp.exe -r n "Animal Pig.nem"
call KENSSharp.exe -r n "Animal Rabbit.nem"
call KENSSharp.exe -r n "Animal Seal.nem"
call KENSSharp.exe -r n "Animal Squirrel.nem"
call KENSSharp.exe -r n "Boss - Eggman after FZ Fight.nem"
call KENSSharp.exe -r n "Boss - Eggman in SBZ2 & FZ.nem"
call KENSSharp.exe -r n "Boss - Exhaust Flame.nem"
call KENSSharp.exe -r n "Boss - Final Zone.nem"
call KENSSharp.exe -r n "Boss - Main.nem"
call KENSSharp.exe -r n "Boss - Weapons.nem"
call KENSSharp.exe -r n "Continue Screen Sonic.nem"
call KENSSharp.exe -r n "Continue Screen Stuff.nem"
call KENSSharp.exe -r n "Ending - Credits.nem"
call KENSSharp.exe -r n "Ending - Emeralds.nem"
call KENSSharp.exe -r n "Ending - Flowers.nem"
call KENSSharp.exe -r n "Ending - Sonic.nem"
call KENSSharp.exe -r n "Ending - StH Logo.nem"
call KENSSharp.exe -r n "Ending - Try Again.nem"
call KENSSharp.exe -r n "Enemy Ball Hog.nem"
call KENSSharp.exe -r n "Enemy Basaran.nem"
call KENSSharp.exe -r n "Enemy Bomb.nem"
call KENSSharp.exe -r n "Enemy Burrobot.nem"
call KENSSharp.exe -r n "Enemy Buzz Bomber.nem"
call KENSSharp.exe -r n "Enemy Caterkiller.nem"
call KENSSharp.exe -r n "Enemy Chopper.nem"
call KENSSharp.exe -r n "Enemy Crabmeat.nem"
call KENSSharp.exe -r n "Enemy Jaws.nem"
call KENSSharp.exe -r n "Enemy Motobug.nem"
call KENSSharp.exe -r n "Enemy Newtron.nem"
call KENSSharp.exe -r n "Enemy Orbinaut.nem"
call KENSSharp.exe -r n "Enemy Roller.nem"
call KENSSharp.exe -r n "Enemy Splats.nem"
call KENSSharp.exe -r n "Enemy Yadrin.nem"
call KENSSharp.exe -r n "Explosion.nem"
call KENSSharp.exe -r n "Fireballs.nem"
call KENSSharp.exe -r n "Game Over.nem"
call KENSSharp.exe -r n "GHZ Breakable Wall.nem"
call KENSSharp.exe -r n "GHZ Bridge.nem"
call KENSSharp.exe -r n "GHZ Edge Wall.nem"
call KENSSharp.exe -r n "GHZ Flower Stalk.nem"
call KENSSharp.exe -r n "GHZ Giant Ball.nem"
call KENSSharp.exe -r n "GHZ Purple Rock.nem"
call KENSSharp.exe -r n "GHZ Spiked Log.nem"
call KENSSharp.exe -r n "GHZ Swinging Platform.nem"
call KENSSharp.exe -r n "Giant Ring Flash.nem"
call KENSSharp.exe -r n "Hidden Bonuses.nem"
call KENSSharp.exe -r n "Hidden Japanese Credits.nem"
call KENSSharp.exe -r n "HUD - Life Counter Icon.nem"
call KENSSharp.exe -r n "HUD.nem"
call KENSSharp.exe -r n "Invincibility Stars.nem"
call KENSSharp.exe -r n "Lamppost.nem"
call KENSSharp.exe -r n "LZ 32x16 Block.nem"
call KENSSharp.exe -r n "LZ 32x32 Block.nem"
call KENSSharp.exe -r n "LZ Blocks.nem"
call KENSSharp.exe -r n "LZ Breakable Pole.nem"
call KENSSharp.exe -r n "LZ Bubbles & Countdown.nem"
call KENSSharp.exe -r n "LZ Cork.nem"
call KENSSharp.exe -r n "LZ Flapping Door.nem"
call KENSSharp.exe -r n "LZ Gargoyle & Fireball.nem"
call KENSSharp.exe -r n "LZ Harpoon.nem"
call KENSSharp.exe -r n "LZ Horizontal Door.nem"
call KENSSharp.exe -r n "LZ Rising Platform.nem"
call KENSSharp.exe -r n "LZ Spiked Ball & Chain.nem"
call KENSSharp.exe -r n "LZ Vertical Door.nem"
call KENSSharp.exe -r n "LZ Water & Splashes.nem"
call KENSSharp.exe -r n "LZ Water Surface.nem"
call KENSSharp.exe -r n "LZ Wheel.nem"
call KENSSharp.exe -r n "Monitors.nem"
call KENSSharp.exe -r n "MZ Green Glass Block.nem"
call KENSSharp.exe -r n "MZ Green Pushable Block.nem"
call KENSSharp.exe -r n "MZ Lava.nem"
call KENSSharp.exe -r n "MZ Metal Blocks.nem"
call KENSSharp.exe -r n "MZ Switch.nem"
call KENSSharp.exe -r n "Points.nem"
call KENSSharp.exe -r n "Prison Capsule.nem"
call KENSSharp.exe -r n "Rings.nem"
call KENSSharp.exe -r n "SBZ Collapsing Floor.nem"
call KENSSharp.exe -r n "SBZ Crushing Girder.nem"
call KENSSharp.exe -r n "SBZ Electrocuter.nem"
call KENSSharp.exe -r n "SBZ Flaming Pipe.nem"
call KENSSharp.exe -r n "SBZ Junction Wheel.nem"
call KENSSharp.exe -r n "SBZ Large Horizontal Door.nem"
call KENSSharp.exe -r n "SBZ Pizza Cutter.nem"
call KENSSharp.exe -r n "SBZ Running Disc.nem"
call KENSSharp.exe -r n "SBZ Sliding Floor Trap.nem"
call KENSSharp.exe -r n "SBZ Small Vertical Door.nem"
call KENSSharp.exe -r n "SBZ Spinning Platform.nem"
call KENSSharp.exe -r n "SBZ Stomper.nem"
call KENSSharp.exe -r n "SBZ Trapdoor.nem"
call KENSSharp.exe -r n "SBZ Vanishing Block.nem"
call KENSSharp.exe -r n "Sega Logo (JP1).nem"
call KENSSharp.exe -r n "Sega Logo.nem"
call KENSSharp.exe -r n "Shield.nem"
call KENSSharp.exe -r n "Signpost.nem"
call KENSSharp.exe -r n "SLZ 32x32 Block.nem"
call KENSSharp.exe -r n "SLZ Breakable Wall.nem"
call KENSSharp.exe -r n "SLZ Cannon.nem"
call KENSSharp.exe -r n "SLZ Fan.nem"
call KENSSharp.exe -r n "SLZ Little Spikeball.nem"
call KENSSharp.exe -r n "SLZ Pylon.nem"
call KENSSharp.exe -r n "SLZ Seesaw.nem"
call KENSSharp.exe -r n "SLZ Swinging Platform.nem"
call KENSSharp.exe -r n "Special 1UP.nem"
call KENSSharp.exe -r n "Special Birds & Fish.nem"
call KENSSharp.exe -r n "Special Clouds.nem"
call KENSSharp.exe -r n "Special Emerald Twinkle.nem"
call KENSSharp.exe -r n "Special Emeralds.nem"
call KENSSharp.exe -r n "Special Ghost.nem"
call KENSSharp.exe -r n "Special Glass.nem"
call KENSSharp.exe -r n "Special GOAL.nem"
call KENSSharp.exe -r n "Special R.nem"
call KENSSharp.exe -r n "Special Red-White.nem"
call KENSSharp.exe -r n "Special Result Emeralds.nem"
call KENSSharp.exe -r n "Special UP-DOWN.nem"
call KENSSharp.exe -r n "Special W.nem"
call KENSSharp.exe -r n "Special Walls.nem"
call KENSSharp.exe -r n "Special ZONE1.nem"
call KENSSharp.exe -r n "Special ZONE2.nem"
call KENSSharp.exe -r n "Special ZONE3.nem"
call KENSSharp.exe -r n "Special ZONE4.nem"
call KENSSharp.exe -r n "Special ZONE5.nem"
call KENSSharp.exe -r n "Special ZONE6.nem"
call KENSSharp.exe -r n "Spikes.nem"
call KENSSharp.exe -r n "Spring Horizontal.nem"
call KENSSharp.exe -r n "Spring Vertical.nem"
call KENSSharp.exe -r n "Switch.nem"
call KENSSharp.exe -r n "SYZ Bumper.nem"
call KENSSharp.exe -r n "SYZ Large Spikeball.nem"
call KENSSharp.exe -r n "SYZ Small Spikeball.nem"
call KENSSharp.exe -r n "Title Cards.nem"
call KENSSharp.exe -r n "Title Screen Foreground.nem"
call KENSSharp.exe -r n "Title Screen Sonic.nem"
call KENSSharp.exe -r n "Title Screen TM.nem"
call KENSSharp.exe -r n "Unused - Eggman Ending.nem"
call KENSSharp.exe -r n "Unused - Explosion.nem"
call KENSSharp.exe -r n "Unused - Fireball.nem"
call KENSSharp.exe -r n "Unused - GHZ Block.nem"
call KENSSharp.exe -r n "Unused - GHZ Log.nem"
call KENSSharp.exe -r n "Unused - Goggles.nem"
call KENSSharp.exe -r n "Unused - Grass.nem"
call KENSSharp.exe -r n "Unused - LZ Sonic.nem"
call KENSSharp.exe -r n "Unused - MZ Background.nem"
call KENSSharp.exe -r n "Unused - Smoke.nem"
call KENSSharp.exe -r n "Unused - SStage Flash.nem"
call KENSSharp.exe -r n "Unused - SYZ Sparkles.nem"
